### ISSUE TITLE
IOS 16.1 error

### ISSUE THREAD

**Issue by gmum4d** [lwitzani/homebridgeStatusWidget#49]
FYI Home script has stopped working on the latest iOs16.1 beta. It was fine on ios16 but the .1 has broken it

**Comment by gmum4d** [comment]
![Uploading AEC092C5-3902-4217-AE5E-649D7E640759.png…]()

**Comment by lwitzani** [comment]
Yeah thanks for the notice. Is it working if you execute it in the scriptable app? My guess is that it is not problem of the script but rather the scriptable app itself. Will probably be fixed in future ios or Scriptable versions automatically

**Comment by gmum4d** [comment]
Hi. I think it’s the app too. I notified them as well and they replied and said it’s most likely the script. 🤣I’m sure an update soon will fix it. Thanks for the great work, love this script, very helpful👍🏻GaryOn 17 Sep 2022, at 09:33, lwitzani ***@***.***> wrote:﻿
Yeah thanks for the notice. Is it working if you execute it in the scriptable app? My guess is that it is not problem of the script but rather the scriptable app itself. Will probably be fixed in future ios or Scriptable versions automatically

**Comment by gmum4d** [comment]
FYI,  a shot video to show what happensGaryOn 17 Sep 2022, at 09:58, Gary Mumford ***@***.***> wrote:﻿Hi. I think it’s the app too. I notified them as well and they replied and said it’s most likely the script. 🤣I’m sure an update soon will fix it. Thanks for the great work, love this script, very helpful👍🏻GaryOn 17 Sep 2022, at 09:33, lwitzani ***@***.***> wrote:﻿
Yeah thanks for the notice. Is it working if you execute it in the scriptable app? My guess is that it is not problem of the script but rather the scriptable app itself. Will probably be fixed in future ios or Scriptable versions automatically

**Comment by njuart** [comment]
Hey, it looks like it's still doesn't work =( Widget itself doesn't show anything, but in the app it executes correctly. I'm on 16.1 beta already.

**Comment by radeonx1800** [comment]
> Hey, it looks like it still doesn't work =( Widget itself doesn't show anything, but in the app it executes correctly. I'm on 16.1 beta also.

Same, occurs on both beta and public releases.

**Comment by radeonx1800** [comment]
iOS 16.1 public beta 4 resolved the issue for me.

**Comment by lwitzani** [comment]
> iOS 16.1 public beta 4 resolved the issue for me.

Glad to hear. Just as i said in my first comment 😅.

**Comment by gmum4d** [comment]
Brilliant. You was spot on👍🏻. It’s great to have it backGaryOn 5 Oct 2022, at 07:08, lwitzani ***@***.***> wrote:﻿

iOS 16.1 public beta 4 resolved the issue for me.

Glad to hear. Just as i said in my first comment 😅.
